config/routes.rb
Rails.application.routes.draw do
  resources :countries
  root "countries#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :social_network, as: :sociable
  accepts_nested_attributes_for :social_network, reject_if: :all_blank, allow_destroy: true

  has_one_attached :icon
  has_one_attached :flag
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Attributes::Dynamic
  include Rails.application.routes.url_helpers

  mount_uploader :media, ImageUploader, mount_on: :media_filename
end

app/models/social_network.rb
class SocialNetwork < ApplicationRecord
  #belongs_to :sociable, polymorphic: true, optional: true
  
  has_one_attached :icon
  has_one_attached :flag

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
    #@country.sociable.build
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)
    #@country.social_networks = SocialNetworks.new(social_networks_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to country_url(@country), notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params) #|| @country.social_networks.update(social_networks_params)
        format.html { redirect_to country_url(@country), notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    def social_networks_params
      params.require(:social_network).permit(:id, :icon, :url, :description)
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(
        :name, :iso, :flag,
        social_networks_attributes: [
          :id, 
          :icon, 
          :url, 
          :description, 
          :sociable_id, 
          :_destroy
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for @country do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :iso %>
    <%= form.text_field :iso %>
  </div>

  <div class="field">
    <%= form.label :flag %>
    <%= form.file_field :flag %>
  </div>
<br />

<hr>

<h2>agregar redes sociales</h2>

<div id="sociales">
<%= form.fields_for :social_networks do |f| %>
  <%= render 'countries/social_networks_fields', f: f %>
<% end %>

<div class="links">
  <%= link_to_add_association 'add red social', form, :social_network,  partial: 'countries/social_networks_fields' %>
</div>

<hr>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/_social_networks_fields.html.erb
<div class="nested-fields">
  <%#= form.fields_for :social_networks, @country.social_networks.build do |builder| %>
    <%
=begin%>
 <%= builder.label :url %>
    <%= builder.url_field :url %>

    <%= builder.label :icon %>
    <%= builder.file_field :icon %>

    <%= builder.label :description %>
    <%= builder.text_area :description %>

    <%= link_to_remove_association "remove task", builder %> 
<%
=end%>
  <%# end %>
<div class="field">
  <%#= form.fields_for :social_networks do |f| %>
    <%= f.label :url %>
    <%= f.url_field :url %>

    <%= f.label :icon %>
    <%= f.file_field :icon %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= link_to_remove_association "remove task", f %> 
  <%# end %>
</div>

</div>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>
<% @countries.each do |country| %>
    <p>Name: <%= country.name %>
    <p>ISO: <%= country.iso %></p>
    <p>Flag: <img src="<%= country.flag %>" alt="flag image"></p>
    <p><%= link_to 'Show', country %> | <%= link_to 'Edit', edit_country_path(country) %> | <%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></p></p>

  <div class="links float-right" style="margin-bottom: 30px;">
    <%#= link_to_remove_association "remove task", f, class: 'btn btn-primary btn-xs' %>   
  </div>


<% end %>
<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%#= render 'social_networks_fields' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Iso:</strong>
  <%= @country.iso %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @country.flag %>
  <%#= image_tag @country.flag %>
  <%#= image_tag @country.flag if @country.flag.attached? %>
  <%#= image_tag (@country.flag), width: "150px", height: "100px" %>
</p>

<p>
  <% @country.social_networks.each do |sociable| %>
    <strong>icon:</strong>
    <%= sociable.icon %>
    <%#= image_tag sociable.icon %>
    <%#= image_tag(sociable.icon) if sociable.icon.attached? %>
    <%#= image_tag url_for(pro_near.icon.attachment) %>
<br />
    <strong>url:</strong>
    <%= sociable.url %>
<br />    
    <strong>description:</strong>
    <%= sociable.description %>
  <% end %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedFormCocoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>